version: '2'

services:

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 5000
      APP_DEBUG: 1
      MYSQL_USER: goliath
      MYSQL_PASS: goliath
      MYSQL_DB: bi_online_shop
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
    links:
      - mysql:mysql

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: bi_online_shop
      MYSQL_ROOT_PASSWORD: goliath
      MYSQL_USER: goliath
      MYSQL_PASSWORD: goliath